### ISSUE TITLE
cpa verify error help.  

### ISSUE THREAD

**Issue by RPalejiya** [microsoft/Mastering-the-Marketplace#109]
We are trying to create AKS offer for marketplace. We are trying to create CNAB bundle using buddling container described in article https://microsoft.github.io/Mastering-the-Marketplace/container/Labs/lab2-create-cnab-bundle-package/ .

We cleared many errors on UI definition, Helm Chart and Manifest but it runs into following error. It doesn't have any indication of where the problem is. Can someone tell how to diagnose the issue further or what is the problem? Is the code for cpa tool available online to debug?

```
root@eee52aa32608:/data# cpa verify       
By using the Azure Kubernetes CNAB Packaging Application, you agree to the License contained in the application. You can view the License at ~/LICENSE. We collect telemetry data, if you would 
like to opt out of data collection please use the --telemetryOptOut flag

Manifest file validated, 0 total failure(s)

Helm chart validated, 0 total failure(s)
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
dev.azure.com/ClusterConfigurationAgent/container-package-app/_git/container-package-app-external/pkg/verify.(*armttkTestResults).toErrors(...)
        /__w/1/s/pkg/verify/arm-ttk.go:94
dev.azure.com/ClusterConfigurationAgent/container-package-app/_git/container-package-app-external/pkg/verify.(*MarketplacePackage).Verify(0xc0017b3c70)
        /__w/1/s/pkg/verify/arm_template.go:63 +0x7d8
dev.azure.com/ClusterConfigurationAgent/container-package-app/_git/container-package-app-external/pkg/verify.(*ArmTemplateVerifier).Verify(0xc0017b3c50)
        /__w/1/s/pkg/verify/arm_template.go:95 +0x139
dev.azure.com/ClusterConfigurationAgent/container-package-app/_git/container-package-app-external/cmd.handleVerifyTemplates({0xc000056004?, 0xc000684fe0?}, 0xc00005400f?)
        /__w/1/s/cmd/verify.go:99 +0xf5
dev.azure.com/ClusterConfigurationAgent/container-package-app/_git/container-package-app-external/cmd.verifyArtifacts(0x0?)
        /__w/1/s/cmd/verify.go:61 +0xf0
dev.azure.com/ClusterConfigurationAgent/container-package-app/_git/container-package-app-external/cmd.verifyCmd.func1(0xc00033f800?, {0x3b5a760?, 0x0?, 0x0?})
        /__w/1/s/cmd/verify.go:29 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc00033f800, {0x3b5a760, 0x0, 0x0})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x3ae4fa0)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
dev.azure.com/ClusterConfigurationAgent/container-package-app/_git/container-package-app-external/cmd.Execute()
        /__w/1/s/cmd/root.go:40 +0x25
main.main()
        /__w/1/s/main.go:21 +0x17 


```

**Comment by RPalejiya** [comment]
I think issue was in ARM template. Ussing arm-ttk to debug and fix template issue resolves this particular issue.
